### ISSUE TITLE
Add new plan specific content

### ISSUE THREAD

**Issue by terotik** [City-of-Helsinki/aplans#6]
- Organization URL (footer)
- Organization name (organization logo alt-text)
- Actions description (Front hero actions-button)
- Indicators description (Front hero indicators-button)

**Comment by terotik** [comment]
UI issue: https://github.com/City-of-Helsinki/cnh-ui/issues/51

**Comment by juyrjola** [comment]
Here they are: https://aplans.api.hel.ninja/v1/graphql/#query=query%20%7B%0A%20%20plan(id%3A%22hnpolut%22)%20%7B%0A%20%20%20%20generalContent%20%7B%0A%20%20%20%20%20%20ownerUrl%0A%20%20%20%20%20%20ownerName%0A%20%20%20%20%20%20actionShortDescription%0A%20%20%20%20%20%20indicatorShortDescription%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
